dist: trusty
sudo: required
language: node_js
notifications:
  email: false
node_js: '8'

install:
  - npm i
  - pyenv global 3.6.3
  - pip install -U pip
  - pip install awscli

script:
  - npm run build
  - aws s3 rm s3://sheaclose.com --recursive
  - aws s3 cp ./dist/ s3://sheaclose.com/ --recursive
  - aws cloudfront create-invalidation --distribution-id E2H2O2GQ4OX9H1 --paths /*
